### ISSUE TITLE
How to use embedded_list in custom twig template?

### ISSUE THREAD

**Issue by ArminVieweg** [alterphp/EasyAdminExtensionBundle#105]
Hi,
first thank for this very cool extension of EAB!

I'd like to use the embedded_list manually in a custom show view. What works for me is calling this in Twig template:

    {{ easyadmin_render_field_for_show_view(_entity_config.name, entity, _entity_config.show.fields.myField) }}

But I have to configure the field in "show" section to get a resolved config array, which I pass with `_entity_config.show.fields.myField`, which double output the embedded list, when I also want to output `{{ block('show_fields') }}` of extending show template.

Is there a way to configure fields, which get merged with template stuff etc. but without using one of the actual base actions? 

I hope you get my point and can help.
Thanks in advance!

**Comment by alterphp** [comment]
Hi @ArminVieweg !

I'm not sure to understand your desired usage... Using embedded_list whithout defining it in the entity `show` config ? Or directly adding it "manually" in a custom template ?

For second option, I guess what you need is including `@EasyAdminExtension/includes/_include_embedded_list.html.twig` with required variables.

**Comment by ArminVieweg** [comment]
What I actually try to achieve is how to reconfigure the fields to display for each embedded list.

So the embedded list of e.g. invoices in customer has different columns/sortings/actions, than the embedded list in products.

Currently the list settings of the related entity is used always, when just using configuration, right? 

Also, I tried to achieve this custom configured list manually (in a custom action template). On this view I wanted to render the original show action and some fields in different sections in the template. Especially relations, which should became an embedded list.

I was just able to pass a plain list of property names. But because all the default configuration was missing, I got exceptions like "template is null". When I've used the key and took the array from show.properties it worked. But then I got double output. 

As far as I understood the ConfigPass thing, the ability to pass custom properties to be displayed for each usage of embedded list, has to be solved there.

**Comment by alterphp** [comment]
Ok, I see. This is something I'd like to be able to achieve too ;-)

For now, embeddedList is just an include of an existing list... So it's not configurable. What you can do is to define specific `entity` entries in the `easy_admin` configuration, such as :

```
easy_admin:
    entities:
        InvoiceForCustomer:
            list:
                fields:
                    - field1
                    - field2
                    - field3
        InvoiceForProduct:
            list:
                fields:
                    - field1
                    - field3
                    - field4
```

It's maybe not convenient but as long `embeddedList` is relying on `list`, and fields in a list are not dynamically modifiable, this is the better way to achieve this.

Idea not to duplicate entity entries : making columns visibility dynamically configurable in a list, with GET params. Columns will be loaded anyway, but could be hidden depending on the context...
