### ISSUE TITLE
Can't configure form_filter with "choice" type, when field is relation

### ISSUE THREAD

**Issue by ArminVieweg** [alterphp/EasyAdminExtensionBundle#106]
I tried this in YAML config:

```
form_filters:
  - property: relation
    label: Relation
    type: choice
    type_options:
      choices:
        Baum: 1
        Kuchen: 2
```
And got the error: **The option "class" does not exist.** 

This occures because of `\AlterPHP\EasyAdminExtensionBundle\Configuration\ListFormFiltersConfigPass::configureAssociationFilter` method, which always adds "class" and "multiple" options, regardless the current set type.

This condition fixed it for me:

            if ($filterConfig['type'] !== ChoiceType::class) {
                $defaultTypeOptions = [
                    'class' => $associationMapping['targetEntity'],
                    'multiple' => true,
                ];
            } else {
                $defaultTypeOptions = [
                    'multiple' => true,
                ];
            }

            $filterConfig['type_options'] = \array_merge(
                $defaultTypeOptions,
                $filterConfig['type_options'] ?? []
            );

Please tell me, when I should provide a pull request.
Thanks!
