### ISSUE TITLE
Roles not applying 

### ISSUE THREAD

**Issue by JulesR2** [alterphp/EasyAdminExtensionBundle#109]
Symfony 4.2.4, seems like roles for entities work but it doesn't for properties.
E.g. this works

```
Cat:
    class: App\Entity\Cat
    role: ROLE_ADMIN
```

but following does not apply
```
Post:
    class: App\Entity\Post
    controller: App\Controller\AdminController
    list:
        fields:
            - { property: 'visible', role: ROLE_ADMIN }
```

(checked in debugger, roles for the current user are OK)
