### ISSUE TITLE
Form filters question

### ISSUE THREAD

**Issue by JulienMarliac** [alterphp/EasyAdminExtensionBundle#110]
Hi,

I can't make form filters work with Easyadmin 2.1 and I don't really know why. 

Is there any thing to set other than that ? 

```yaml
            list:
                form_filters:
                    - { property: roles, type_options: { choices: { ROLE_ADMIN: admin, ROLE_MANAGER: manager } } }
```
