### ISSUE TITLE
The options "choices_static_callback" on relation field

### ISSUE THREAD

**Issue by BenjaminTappnad** [alterphp/EasyAdminExtensionBundle#119]
Hi,

I have 2 entites:

- The first is "Question" and have many "Answer"
- The second is "Answer". An answer is related to only one question

I want to filter over the "Question" entity on the "Answer" list view.
To do that I firstly added this: 
```YAML
Answer:
  class: App\Entity\Answer
    list:
      form_filters:
        - {property: 'question', label: 'Question'}
```

This is great, it adds me the filter with the input search field to filter over my questions labels...

But all my labels are encrypted on my Database, so this is not human readable until I decrypt it with an utility.

You can see that filtering on that field is not possible, since it will perform an ajax on table and will try to find a human readable label, entered by the user's filtering the list, on an encrypted label in Database.

So what I want is to make a filter which would work exactly like an **easyadmin_autocomplete** field type (when you edit your entity, the generated list can be filtered not by ajax, but by all labels present in the dropdown list).

Finally I tried this:
```YAML
Answer:
  class: App\Entity\Answer
    list:
      form_filters:
        - {property: 'question', label: 'Question', type: choice, type_options: { choices_static_callback: [getQuestionLabels] }}
```

Where I want to find all my questions, looping on it, decryptying all labels, and returning an array with all decrypted labels on the static method **getQuestionLabels** of my Answer entity.

But I get this error:

> The options "choices_static_callback", "class" do not exist

Can you please help me? Maybe I'm totally wrong in my process and there is a better way to perform what I want.

Thanks
