### ISSUE TITLE
More than 1 entity defined in EasyAdmin configuration matches %s FQCN

### ISSUE THREAD

**Issue by qcho** [alterphp/EasyAdminExtensionBundle#130]
Hi. I'm getting this error:
```php
// in vendor/alterphp/easyadmin-extension-bundle/src/Helper/EmbeddedListHelper.php (line 89)

...
if (1 < \count($matchingEntityConfigs)) {
    throw new \RuntimeException(
        \sprintf('More than 1 entity defined in EasyAdmin configuration matches %s FQCN.', $entityFqcn)
    );
}
...
```

The issue here is that having multiple definitions of the same entity, resulting in identical FQCN is encouraged by easy admin for multiple purposes. For example when creating different listings for the same entity
See: https://symfony.com/doc/current/bundles/EasyAdminBundle/book/list-search-show-configuration.html#filtering-entities

```yaml
easy_admin:
    entities:
        VipCustomers:
            class: AppBundle\Entity\User
            list:
                dql_filter: 'entity.budget > 100000'
        RegularCustomers:
            class: AppBundle\Entity\User
            list:
                dql_filter: 'entity.budget <= 100000'
```
Can't the code use it's name instead? `VipCustomers` & `RegularCustomers` and infer it's class from it
