### ISSUE TITLE
Cannot use embedded lists

### ISSUE THREAD

**Issue by paulalbertdev** [alterphp/EasyAdminExtensionBundle#157]
Hi ! 
Dunno if it's a bug or if I'm doing something wrong, but when I try to use an embedded_list like this : 

```
entities:
    BoatOtherImage:
      class: App\Entity\BoatOtherImage
    Boat:
      class: App\Entity\Boat
      label: 'Bateau'
      list:
        fields:
          - { property: 'fullName', label: 'Nom complet' }
          - { property: 'mainPhoto', label: 'Photo principale', sortable: false, type: 'image', base_path: '%app.path.boat_photos_upload_path%' }
        sort: ['position', 'ASC']
      show:
        fields:
          - { property: 'mainPhoto', label: 'Photo principale', type: 'image', base_path: '%app.path.boat_photos_upload_path%' }
          - { property: 'position' }
      form:
        fields:
          - { property: 'brand', label: 'Marque' }
          - { property: 'model', label: 'Modèle' }
          - { property: 'mainPhotoFile', label: 'Photo principale', type: 'vich_image' }
          - { property: 'secondaryPhotoFile', label: 'Photo secondaire', type: 'vich_image' }
          - { property: 'text', label: 'Texte', type: 'fos_ckeditor' }
          - { property: boatOtherImages, label: '', type: embedded_list, type_options: { entity: BoatOtherImage, filters: { 'entity.promoter': 'form:parent.data.id' } } }
```

I get this error : 

> Neither the property "boatOtherImages" nor one of the methods "getBoatOtherImages()", "boatOtherImages()", "isBoatOtherImages()", "hasBoatOtherImages()", "__get()" exist and have public access in class "App\Entity\Boat".

Shouldn't this property/getter be unnecessary since default behavior should be overridden to select another table ? Am I doing something else badly ?

(I'm using v2.1.7 and easyAdminBundle v2.1.4)

Thanks for your time !
