### ISSUE TITLE
Using multiple extensions with EasyAdmin

### ISSUE THREAD

**Issue by DylanKas** [alterphp/EasyAdminExtensionBundle#175]
Hello!

We decided to use this bundle for our project (especially the embedded list feature) and it works great so well done!

We are trying to use some features from [Wandi Extension bundle](https://github.com/WandiParis/EasyAdminPlusBundle) as well but we face some issues configurating both of them at the same time.

We used to have :
```
#routes/easy_admin.yaml
easy_admin_bundle:
  resource: '@EasyAdminExtensionBundle/Controller/EasyAdminController.php'
  prefix: /admin
  type: annotation
```
And it was fine when using only this bundle. However, now we want to use this bundle as well as the one quoted previously but it also need to replace the easyadmin controller by the one from the new bundle.

So both extension wants to do the same thing and both extends the BaseAdminController from EasyAdmin.

What would be the best way to use both in a same project ?
Maybe having an usable trait to use instead of extending the Controller would work so that we could juste use the two traits instead of trying to basically extends 2 controller ?

Thanks in advance.
