### ISSUE TITLE
Add easyadmin_admin_roles in documentation

### ISSUE THREAD

**Issue by gonzakpo** [alterphp/EasyAdminExtensionBundle#61]
**security.yaml**
```yaml
    role_hierarchy:
        ROLE_USER: ROLE_USER
        ROLE_ADMIN: [ROLE_ADMIN, ROLE_USER]
        ROLE_SUPER_ADMIN: ROLE_ADMIN
```
**Generated Form:**
- ROLE_USER
- - ROLE_USER (checkbox)
- ROLE_ADMIN
- - ROLE_ADMIN (checkbox)
- - ROLE_USER (checkbox)

**its correct?**
