### ISSUE TITLE
Security for all type "except entity" if has rol only hide menu

### ISSUE THREAD

**Issue by gonzakpo** [alterphp/EasyAdminExtensionBundle#75]
It's a custom action to a route like do to hide in the menu by role:
```yaml
easy_admin:
        menu:
            - { label: 'App action', route: 'app_action', role: ROLE_SUPER_ADMIN }
```
It does not work
