### ISSUE TITLE
[v2] Filters do not expand

### ISSUE THREAD

**Issue by IonBazan** [alterphp/EasyAdminExtensionBundle#88]
In v2.0 filters do not expand upon click and remain collapsed. This is caused by https://github.com/EasyCorp/EasyAdminBundle/commit/ea513998d03e106695f545d705a23e3ba4b5e10d#diff-8b95a20e21550730e7b5557f56908c73R6 - only `modal`, `tab`, `tooltip` and `popover` are now imported and the `collapse` is missing.

**Comment by alterphp** [comment]
Hi @IonBazan,

By default, EasyAdmin now embed a limited version of Bootstrap JS. It may be changed by modifying the JS file being loaded :

```yaml
easy_admin:
    design:
        assets:
            css:
                - 'bundles/easyadmin/bootstrap-all.css'
                - 'bundles/easyadminextension/stylesheet/full-width.css'
            js:
                - 'bundles/easyadmin/bootstrap-all.js'
```
