### ISSUE TITLE
Embedded list filter not working

### ISSUE THREAD

**Issue by pesseyjulien** [alterphp/EasyAdminExtensionBundle#94]
Hi,

I'm having trouble with one embedded list filter, declared as followed :

`- { property: 'jobs', label: '', type: 'embedded_list', type_options: { entity: 'Job', filters: { 'entity.company_vendor': 'form:parent.data.worker_company.id' }} }`

But it will generate a request like this :

`localhost/admin/?entity=Job&action=list&filters%5Bentity.author%5D=19651a30-2b6d-11e8-aa77-24adf7d02a63&filters%5Bentity.company_vendor%5D=12117956-2b70-11e8-aa77-24adf7d02a63&sortField=start_date&sortDirection=DESC`

AS you can see, it will always incude 'entity.author' in the filters, even if I do not declare it.

Any idea why ?

Thanks in advance,
Julien

**Comment by alterphp** [comment]
Hi @pesseyjulien !

Can I see the easy_admin config for entity `Job` ?

**Comment by pesseyjulien** [comment]
Here you go :

`easy_admin:
    entities:
        Job:
            disabled_actions: ['new']
            class: AppBundle\Entity\Job
            #search:
                #fields: ['number', 'company_vendor.company_name', 'company_client.company_name', 'current_status.status.label']
            delete:
                role: ROLE_SUPER_ADMIN
            list:
                actions:
                    - { name: 'export', icon: '', label: '' }
                sort: ['start_date', 'DESC']
                fields:
                    - {property: 'number', label: 'N°'}
                    - {property: 'current_status', label: 'Statut', template: '@App/Admin/status_color_job.html.twig'}
                    - {property: 'company_vendor', label: 'Worker'}
                    - {property: 'company_client', label: 'Entreprise'}
                    - {property: 'start_date', label: 'Date de début'}
                    - {property: 'end_date', label: 'Date de fin'}
                    - {property: 'category', label: 'Catégorie'}
                    - {property: 'total_gross_worker', label: 'Gain Worker Brut'}
                    - {property: 'total_costs_pro', label: 'Coûts Pro'}
                    - {property: 'createdAt', label: 'Date création', type: 'date'}


            edit:
                fields:
                    - { type: 'tab', label: 'Général'}
                    - { type: 'group', label: 'Statuts', columns: 6, }
                    - { property: 'current_status', label: 'Statut actuel', type: 'entity', type_options: { class: 'AppBundle\Entity\StatusDetails', multiple: false, required: true, block_name: 'custom_status'}}
                    - { property: 'previous_status', label: 'Ancien statuts', type: 'embedded_list', type_options: { entity: 'StatusDetails', filters: { 'entity.job': 'form:parent.data.id' }} }
                    - { type: 'group', label: 'Dates', columns: 6, }
                    - { property: 'start_date', label: 'Date début', type_options: { block_name: 'custom_date', required: true }}
                    - { property: 'end_date', label: 'Date fin', type_options: { block_name: 'custom_date', required: true }}
                    - { property: 'total_min', label: 'Durée (min)', type: 'number', type_options: {disabled: true}}
                    - { type: 'group', label: 'Address', columns: 6, }
                    - { property: 'address', label: 'Adresse'}
                    - { property: 'city', label: 'Ville'}
                    - { property: 'postal_code', label: 'Code Postal'}
                    - { property: 'country', label: 'Pays'}
                    - { type: 'group', label: 'Descriptif', columns: 6, }
                    #- { property: 'company_vendor', label: 'Vendeuse', type: 'embedded_list', type_options: { entity: 'Company', filters: { 'entity.company_vendor': 'form:parent.data.id' }} }
                    - { property: 'company_vendor', label: 'Worker', type_options: { disabled: true}}
                    - { property: 'company_client', label: 'Pro', type_options: { disabled: true}}
                    - { property: 'category', label: 'Catégorie', type_options: { disabled: true}}
                    - { property: 'description', label: 'Description', type_options: {disabled: false}}


                    - { type: 'tab', label: 'Facturation'}
                    - { type: 'group', label: 'Worker', columns: 4, }
                    - { property: 'rate_worker', label: 'Taux', type: 'money', type_options: { currency: 'EUR', disabled: true}}
                    - { property: 'total_net_worker', label: 'Total net', type: 'money', type_options: { currency: 'EUR', disabled: true}}
                    - { property: 'total_charges_worker', label: 'Charges', type: 'money', type_options: { currency: 'EUR', disabled: true}}
                    - { property: 'total_gross_worker', label: 'Total brut', type: 'money', type_options: { currency: 'EUR', disabled: true}}
                    - { type: 'group', label: 'Pro', columns: 4, }
                    - { property: 'rate_pro', label: 'Taux', type: 'money', type_options: { currency: 'EUR', disabled: false}}
                    - { property: 'total_costs_pro', label: 'Total', type: 'money', type_options: { currency: 'EUR', disabled: true}}
                    - { property: 'discount', label: 'Promo', type: 'money', type_options: { currency: 'EUR', block_name: 'custom_discount'}}
                    - { type: 'group', label: 'My Works', columns: 4, }
                    - { property: 'rate_commission_myworks', label: 'Taux Com.', type: 'money', type_options: { currency: 'EUR', disabled: true}}
                    - { property: 'total_commission_myworks', label: 'Total Com.', type: 'money', type_options: { currency: 'EUR', disabled: true}}
                    - { type: 'group', columns: 12, label: 'Facture'}
                    - { property : 'rate_unit', label: 'Unité', type: 'Symfony\Component\Form\Extension\Core\Type\ChoiceType', type_options: { expanded: false, multiple: false, choices: {'Horaire' : 'eurPerHour', 'Forfait' : 'eurPerPerformance'}}}
                    #- { property: 'invoice', label: 'Facture', type: 'entity', type_options: { class: 'AppBundle\Entity\Invoice', disabled: true}}
                    - { property: 'invoice_items', label: 'Factures', type: 'embedded_list', type_options: { entity: 'InvoiceItem', filters: { 'entity.job': 'form:parent.data.id' }} }

                    - { type: 'tab', label: 'Details'}
                    - { type: 'group', label: 'Informations techniques', columns: 6, }
                    - { property: 'author', label: 'Auteur', type: 'entity', type_options: { class: 'AppBundle\Entity\User', disabled: true}}
                    #- { property: 'contract', label: 'Contract', type_options: {data_class : null, block_name: 'custom_file'}}
                    - { property: 'createdAt', label: 'Date de création',  type_options: {disabled: true}}
                    - { property: 'updatedAt', label: 'Date de mise à jour',  type_options: {disabled: true}}`

**Comment by alterphp** [comment]
Where does the URL come from ? It is not coming from an embedded list as `action` is list and not `embeddedList`.

**Comment by pesseyjulien** [comment]
The link is coming from under the table (see screenshot) : 'open in a new tab'.

![capture d ecran 2019-01-28 a 16 17 02](https://user-images.githubusercontent.com/10850944/51845644-31035500-2318-11e9-9809-ff8afc7a0e1b.jpg)

**Comment by alterphp** [comment]
So I think this is expected behavior :
- The embedded list shown above is filtered on the author of the job offer
- The link "open in a new tab" opens the same filtered list (filtered on the author)
- The form list filters apply along request filters so they are combined when submitted.

If you open your job offers list from its main entry, something like /admin?entity=Job&action=list, it should not be filtered on author.

Am I right ?

**Comment by pesseyjulien** [comment]
Well, the goal was to display the jobs (as embedded list) inside the 'worker' edit view. So the filter rule should be 'entity.company_vendor': 'form:parent.data.worker_company.id' but it automatically adds the 'author' filter.

**Comment by alterphp** [comment]
Looks weird indeed... Could you paste the full easy_admin config, and the Worker entity ?

**Comment by pesseyjulien** [comment]
```
easy_admin:
    site_name: 'My Works Back-Office'
    formats:
        date: 'd/m/Y'
        time: 'h:i'
        datetime: 'd/m/Y H:i'
    list:
        actions:
            - { name: 'edit', icon: 'pencil', label: '' }
            - { name: 'delete', icon: 'trash', label: '' }
    design:
        assets:
          css:
            - 'bundles/easyadmin/bootstrap-all.css'
            - 'bundles/app/css/admin.css'
          js:
            - 'bundles/easyadmin/bootstrap-all.js'

        templates:
          layout: '@App/Admin/layout.html.twig'
          list: '@App/Admin/list.html.twig'
          edit: '@App/Admin/edit.html.twig'

        form_theme:
          - '@App/Admin/form.html.twig'
          - '@EasyAdmin/form/bootstrap_4.html.twig'

        menu:
          #- { label: 'application', url: 'https://app.myworks.fr/login', rel : "external", target: '_blank'}
          
          - { label: 'Prestations' }
          - { entity: 'Offer', icon: 'bullhorn'}
          - { entity: 'Job', icon: 'globe'}

          - { label : 'Utilisateurs' }
          - { entity: 'Worker', icon: 'user'}
          - { entity: 'Pro', icon: 'briefcase' }
          - label: 'Details Utilisateurs'
            icon: 'info'
            children:
              - { entity: 'Experience', label: 'Experiences', icon: 'briefcase' }
              - { entity: 'Diploma', label: 'Diplomes', icon: 'graduation-cap' }
              #- { entity: 'Availability', label: 'Dispos', icon: 'clock-o' }
              - { entity: 'Skill', label: 'Compétences', icon: 'tasks' }
              - { entity: 'Profile', label: 'Profils', icon: 'id-badge' }

          - { label : 'Entreprises' }
          - { entity: 'AE', label: 'Auto-Entreprises', icon: 'address-card' }
          - { entity: 'Establishment', label: 'Etablissements', icon: 'building' }
          - { entity: 'Bank', label: 'Banques', icon: 'university' }


          - { label : 'Comptabilité' }
          - { entity: 'Revenues', label: 'Revenues', icon: 'dollar'}
          - { entity: 'Invoice', label: 'Facture', icon: 'file' }
          - { entity: 'Transaction', icon: 'exchange'}
          - { entity: 'Service', icon: 'book'}
          - { entity: 'TaxRate', label: 'Commission', icon: 'credit-card'}

          - { label : 'Admin' }
          - { entity: 'User', icon: 'users', label: 'Users'}


easy_admin_extension:
    custom_form_types:
        embedded_list: AlterPHP\EasyAdminExtensionBundle\Form\Type\EasyAdminEmbeddedListType
```

**Comment by pesseyjulien** [comment]
```
easy_admin:
    entities:
        Worker:
            disabled_actions: ['new']
            class: AppBundle\Entity\User
            list:
                form_filters:
                  - { name: lastLoginAfter, property: lastLogin, operator: gte, type: datetime }
                actions:
                  - { name: 'logas', label: '', icon: 'external-link-square', target: '_blank' }
                  - { name: 'export', icon: '', label: '' }
                sort: 'lastLogin'
                fields:
                  - { property: 'enabled', label: 'Enabled'}
                  - { property: 'isVisible', label: 'Visible'}
                  - { property: 'username', label: 'Nom utilisateur'}
                  - { property: 'firstName', label: 'Prénom'}
                  - { property: 'lastName', label: 'Nom'}
                  - { property: 'email', label: 'Email'}
                  - { property: 'lastLogin', label: 'Dernière connexion', type: 'datetime'}
                  - { property: 'worker_company', label: 'Auto-Entreprise'}
                  - { property: 'bde', label: 'BDE'}
                  - { property: 'aeSubscription', label: 'Tunnel', type : 'boolean'}
                  - { property: 'categories[0].rate_worker', label: 'Taux rem'}
                  #- { property: 'profiles', template: 'profiles.html.twig' }

            form:
                fields:
                  - { type: 'tab', label: 'Général'}
                  - { type: 'group', columns: 6, }
                  - { property: 'username', label: 'Username', type: 'text', type_options: {disabled: true}}
                  - { property: 'firstName', label: 'Prénom',type: 'text', type_options: {required: true}}
                  - { property: 'maidenname', label: 'Nom de jeune fille',type: 'text', type_options: {required: false}}
                  - { property: 'lastName', label: 'Nom',type: 'text', type_options: {required: true}}
                  - { property: 'picture',  label: 'Photo de profil', type_options: {data_class : null, block_name: 'custom_file'}}
                  #- { property: 'email_canonical', type: file, type_options: {data_class : null, block_name: 'hidden_file'}}
                  - { property: 'gender', label: 'Genre',type: 'choice', type_options: { choices: {'Masculin' : 'male', 'Feminin' : 'female'}}}
                  - { property: 'nationality', label: 'Nationalité', type: 'Symfony\Component\Form\Extension\Core\Type\CountryType'}
                  - { property: 'marital_status', label: 'Situation familiale'}
                  - { type: 'section', label: 'Contact'}
                  - { property: 'email', label: 'Email',type: 'email'}
                  - { property: 'phone_number', label: 'Téléphone', type: 'number', type_options: {required: false}}
                  - { type: 'section', label: 'Domicile'}
                  - { property: 'address', label: 'Adresse'}
                  - { property: 'postal_code', label: 'Code postal'}
                  - { property: 'city', label: 'Ville'}
                  - { property: 'country', label: 'Pays'}
                  #- { property: 'zone', label: 'Zone'}

                  - { type: 'group', columns: 6, }
                  - { type: 'section', label: 'Sécu'}
                  - { property: 'social_regime', label: 'Régime Sécu',type: 'text', type_options: {disabled: false}}
                  - { property: 'social_number', label: 'Numéro sécu',type: 'text', type_options: {disabled: false}}
                  - { type: 'section', label: 'Naissance'}
                  - { property: 'birth_date', label: 'Date', type: 'Symfony\Component\Form\Extension\Core\Type\BirthdayType', type_options: {required: false}}
                  - { property: 'birth_postal_code', label: 'Code postal'}
                  - { property: 'birth_city', label: 'Ville'}
                  - { property: 'birth_dept', label: 'Département'}
                  - { property: 'birth_country', label: 'Pays'}
                  - { type: 'section', label: 'Parents'}
                  - { property: 'father_firstName', label: 'Prénom (père)'}
                  - { property: 'father_lastName', label: 'Nom (père)'}
                  - { property: 'mother_firstName', label: 'Prénom (mère)'}
                  - { property: 'mother_lastName', label: 'Nom (mère)'}

                  - { type: 'tab', label: 'Professionel'}
                  - { type: 'section', label: 'Auto-entreprise'}
                  - { property: 'aeSubscription', label: 'Demande AE via myworks'}
                  - { property: 'worker_company', label: 'Entreprise', type_options: {data_class : null, block_name: 'custom_ae'}}
                  - { type: 'section', label: 'Emploi'}
                  - { property: 'job_status', label: 'Statut',type: 'text', type_options: {disabled: false}}
                  - { property: 'job_position', label: 'Position',type: 'text', type_options: {disabled: false}}


                  - { type: 'tab', label: 'Fichiers', columns: 4, }
                  - { property: 'file_identity', label: "Carte d'identité", help: 'Recto + Verso', type_options: {data_class : null, block_name: 'custom_file'}}
                  - { property: 'file_mandat',  label: 'Mandat', type_options: {data_class : null, block_name: 'custom_file'}}
                  - { property: 'file_ae_declaration', label: 'Cerfa', type_options: {data_class : null, block_name: 'custom_file'}}
                  - { property: 'file_accre_declaration', label: 'Accre', type_options: {data_class : null, block_name: 'custom_file'}}
                  - { property: 'file_insee', label: 'insee', type: file, type_options: {data_class: null, block_name: 'custom_file'}}
                  - { property: 'file_urssaf', label: 'URSSAF', type_options: {data_class: null, block_name: 'custom_file'}}
                  - { property: 'file_end_activity', label: 'Cessation activite', type_options: {data_class: null, block_name: 'custom_file'}}

                  - { type: 'tab', label: 'Expériences'}
                  - { type: 'group', columns: 12, }
                  - { property: 'skills', label: 'Compétences', type: 'entity', type_options: { class: 'AppBundle\Entity\Skill', multiple: true, required: false}}
                  - { type: 'group', label: 'Diplomes', columns: 6, }
                  - { property: 'diplomas', label: '', type: 'embedded_list', type_options: { entity: 'Diploma', filters: { 'entity.user': 'form:parent.data.id' }} }
                  - { type: 'group', label: 'Expériences', columns: 6, }
                  - { property: 'experiences', label: '', type: 'embedded_list', type_options: { entity: 'Experience', filters: { 'entity.user': 'form:parent.data.id' }} }

                  - { type: 'tab', label: 'Catégorie & Dispos'}
                  - { type: 'group', label: 'Catégories', columns: 6, }
                  - { property: 'categories', label: '', type: 'embedded_list', type_options: { entity: 'Category', filters: { 'entity.user': 'form:parent.data.id' }} }
                  - { type: 'group', label: 'Disponibilités', columns: 6, }
                  - { property: 'availabilities', label: '', type: 'embedded_list', type_options: { entity: 'Availability', filters: { 'entity.user': 'form:parent.data.id' }} }

                  - { type: 'tab', label: 'Jobs'}
                  - { type: 'group', label: 'Jobs', columns: 12, }
                  #- { property: 'jobs', label: '', type: 'embedded_list', type_options: { entity: 'Job', filters: { 'entity.company_vendor': 'form:parent.data.worker_company.id' }} }

                  - { type: 'tab', label: 'Admin'}
                  - { type: 'group', label: 'Etat', columns: 3 }
                  - { property: 'enabled', label: 'Enabled'}
                  - { property: 'isVisible', label: 'Visible (recherche)'}
                  - { property: 'isPublic', label: 'public profile (si disable, event user)'}
                  - { property: 'stripe_id', label: 'Stripe ID', type: 'text', type_options: {disabled: true}}
                  - { property: 'locale', label: 'Langue', type: 'Symfony\Component\Form\Extension\Core\Type\LocaleType'}
                  - { type: 'group', label: 'Droits', columns: 4 }
                  - { property: 'profiles', label: 'Profils', type: 'entity', type_options: { class: 'AppBundle\Entity\Profile', multiple: true, required: true}}
                  #- { property : 'roles', label: 'Roles', type: 'Symfony\Component\Form\Extension\Core\Type\ChoiceType', type_options: { expanded: false, multiple: true, choices: {'USER' : 'ROLE_USER', 'ADMIN' : 'ROLE_ADMIN'}}}
                  - { type: 'section', label: 'Changer MDP'}
                  - { property: 'plain_password', type: 'repeated', help: 'Minimum 6 caractères', type_options: { type: 'Symfony\Component\Form\Extension\Core\Type\PasswordType', invalid_message: 'Password must match', first_options: { label: 'Mot de passe' }, second_options: { label: 'Confirmation' }, required: false } }
                  - { type: 'group', label: 'Plus', columns: 5, help: 'A titre informatif - Calculé automatiquement' }
                  - { property: 'last_login', label: 'Date dernière connexion', type: 'date', type_options: {disabled: true}, }
                  - { property: 'createdAt', label: 'Date de création', type: 'date', type_options: {disabled: true}}
                  - { property: 'updatedAt', label: 'Date de mise à jour', type: 'date', type_options: {disabled: true}}
                  - { type: 'section', label: 'Origin'}
                  - { property : 'events', label: 'Events'}
                  - { property : 'bde', label: 'BDE'}
```
