### ISSUE TITLE
Autocomplete add new option 'create' -> does not work for me

### ISSUE THREAD

**Issue by markus-fischbacher** [alterphp/EasyAdminExtensionBundle#98]
Hi there, I'm facing an issue, that the create option for the autocomplete field is not shown.
Saw the issue #91 but unfortunately I'm not dealing with self written templates. I'm using the default ones. Have no idea how I get that working.

![image](https://user-images.githubusercontent.com/10846308/52376931-b4811c80-2a63-11e9-8891-b3fef53828cd.png)

![image](https://user-images.githubusercontent.com/10846308/52377040-fdd16c00-2a63-11e9-899b-ea58d4d50d02.png)

"alterphp/easyadmin-extension-bundle": "^2.1",
"easycorp/easyadmin-bundle": "^2.0",

Any help is appreciated.

Regards
Markus

**Comment by markus-fischbacher** [comment]
Hi @alterphp !

Sure! Please find the info below.

```
routes\easy_admin.yaml

easy_admin_bundle:
    resource: '@EasyAdminExtensionBundle/Controller/EasyAdminController.php'
    prefix: /
    type: annotation

```
```
packages\easy_admin.yaml

imports:
  - { resource: easy_admin/ }
  - { resource: easy_admin/entities/ }
```
```
packages\easy_admin\basic.yaml

easy_admin:
  site_name: 'Portal'
```

```
packages\easy_admin\design.yaml

easy_admin:
  design:
    menu:
      - { label: 'Dashboard', icon: 'tachometer', route: 'dashboard', default: true }
      - label: 'User'
        icon: 'user-o'
        children:
          - { label: 'User', entity: 'User' }
          - { label: 'User Profile', entity: 'UserProfile' }
      - label: 'Address'
        icon: 'address-card-o'
        children:
          - { label: 'City', entity: 'City' }
          - { label: 'Country', entity: 'Country' }
      - label: 'Medical'
        icon: 'user-md'
        children:
          - { label: 'Department', entity: 'Department' }
          - { label: 'Personal Position', entity: 'PersonalPosition' }
          - { label: 'Medical Degree', entity: 'MedicalDegree' }
          - { label: 'Medical Speciality', entity: 'MedicalSpeciality' }
          - { label: 'Medical Subspeciality', entity: 'MedicalSubspeciality' }
      - label: 'Application'
        icon: 'calendar-check-o'
        children:
          - { label: 'Application', entity: 'Application' }
          - { label: 'Application Status', entity: 'ApplicationStatus' }
      - label: 'Program'
        icon: 'wpforms'
        children:
          - { label: 'Program', entity: 'Program' }
          - { label: 'Seminar', entity: 'Seminar' }
          - { label: 'Observership', entity: 'Observership' }
      - label: 'Documents'
        icon: 'file-text-o'
        children:
          - { label: 'Document', entity: 'Document' }
```
```
packages\easy_admin\entities.yaml

easy_admin:
  entities:
    Application:
      class: App\Entity\Application
    ApplicationStatus:
      class: App\Entity\ApplicationStatus
    City:
      class: App\Entity\City
    Country:
      class: App\Entity\Country
    Department:
      class: App\Entity\Department
    Document:
      class: App\Entity\Document
    MedicalDegree:
      class: App\Entity\MedicalDegree
    MedicalSpeciality:
      class: App\Entity\MedicalSpeciality
    MedicalSubspeciality:
      class: App\Entity\MedicalSubspeciality
    Observership:
      class: App\Entity\Observership
    PersonalPosition:
      class: App\Entity\PersonalPosition
    Program:
      class: App\Entity\Program
    Seminar:
      class: App\Entity\Seminar

```
```
packages\easy_admin\formats.yaml

easy_admin:
  formats:
    date: 'd.m.Y'
    datetime: 'd.m.Y h:i'
```
```
packages\easy_admin\entities\user.yaml

easy_admin:
  entities:
    User:
      class: App\Entity\User
      form:
        fields:
          - email
          - { property: 'roles', type: 'App\Form\RoleType', type_options: { expanded: true, multiple: true } }
          - { property: 'userProfile', type: 'easyadmin_autocomplete', type_options: { attr: { create: true } } }

```
```
packages\easy_admin\entities\user_profile.yaml

easy_admin:
  entities:
    UserProfile:
      class: App\Entity\UserProfile
      form:
        fields:
          - user
          - firstName
          - lastName
          - { property: sex, type: 'App\Form\GenderType', type_options: { expanded: false, multiple: false } }
          - { property: birthDate, type: 'App\Form\BirthdayType' }
          - homePhone
          - homeStreet
          - homeZipCode
          - homeCity
          - homeCountry
          - passportNumber
          - personalPosition
          - academicPosition
          - medicalSpeciality
          - medicalSubspeciality
          - institution
          - department
          - otherSpeciality
          - otherSubspeciality
          - otherDepartment
          - workStreet
          - workZipCode
          - workCity
          - workCountry
          - profilePhoto
          - medicalLicenseNumber
          - medicalLicenseIssueDate
          - numberPublications
          - numberEnglishPublications
          - applications

```
